[package]
name = "wsb-rs"
version = "0.1.0"
authors = ["Alexander Vitiuk"]
description = "Calculates when your options will print."
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
